### ISSUE TITLE
Basic Structure

### ISSUE THREAD

**Issue by RedRoboHood** [skylight-software/jonathan-server#4]
How will Jonathan work, at least in initial stages? Will we serve the user a webpage that allows them to send "queries" (term used loosely) to a server, which then will serve them back a webpage? Do we want to use [GitHub Pages](https://help.github.com/categories/github-pages-basics/) (i.e. should we rename the master branch to gh-pages)?

**Comment by miller9904** [comment]
Jonathan will be in three major parts: Jonathan Cloud, Jonathan Server, and Jonathan Client.

### Jonathan Cloud
Jonathan cloud will be hosted on our own cloud structure (which I have no idea how we'll implement right now.)  We will only host APIs that require very large datasets or lots of computing power.  I opened a seperate issue for the domain name here: #5.

### Jonathan Server
Jonathan Server is what the user loads onto their computer to host computations and curate information.  I'm still not sure what exactly this will be, because some of the stuff I'm thinking about is only supported on Linux.  This software will control all the settings and such, as well as being it's own client.

### Jonathan Client
Jonathan Client is the name given to any of the client apps for Jonathan.  Right now, I'm building a Windows Universal app and a web interface, but I'm hoping we'll get clients on many more platforms.  The server and the clients will be connected through a routing server in the Jonathan Cloud.

**Comment by RedRoboHood** [comment]
Makes sense. Will this repository hold the code for the cloud, the server, or both?

**Comment by miller9904** [comment]
That's what I was wondering.  Probably the server.  Should we rename it jonathan-server, then?  I planned to keep each part separate, like jonathan-cloud, jonathan-server, jonathan-windows, and jonathan-android.

**Comment by RedRoboHood** [comment]
Sounds good to me. I'm renaming the repository now.

**Comment by miller9904** [comment]
OK.
